using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using shipapp.Models.ModelData;

namespace shipapp.Models
{
    /// <summary>
    /// Vendor Model Class
    /// </summary>
    class Vendors
    {
        /// <summary>
        /// Autogenerated Id Do not modify
        /// </summary>
        public long VendorId { get; set; }
        /// <summary>
        /// Vendor Name as string
        /// </summary>
        public string VendorName { get; set; }
        public Vendors()
        {
        }
        public override string ToString()
        {
            return VendorName;
        }
    }
}
